using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace MoviesManagement.Helpers
{
    public class OptionListService : IOptionListService
    {
        public IList<SelectListItem> GetCategories()
        {
            var categories = new string[]
            {
                "baśń filmowa",
"Czarna Komedia",
"dramat biograficzny",
"dramat historyczny",
"Dramat Katastroficzny",
"dramat kostiumowy",
"dramat kryminalny",
"Dramat Obyczajowy",
"Dramat Polityczny",
"Dramat Przygodowy",
"Dramat Psychologiczny",
"dramat sensacyjny",
"Dramat Sf",
"dramat wojenny",
"Film Animowany",
"film animowany dla dorosłych",
"film biograficzny",
"Film Dokumentalny",
"Film Familijny",
"film fantasy",
"Film Historyczny",
"film katastroficzny",
"Film Kostiumowy",
"Film Krótkometrażowy",
"film kryminalny",
"film muzyczny",
"film obyczajowy",
"film przygodowy",
"Film Psychologiczny",
"film religijny",
"Film Sensacyjny",
"film sf",
"film wojenny",
"horror",
"horror komediowy",
"horror sf",
"komedia",
"Komedia Fantasy",
"Komedia Historyczna",
"komedia kryminalna",
"komedia muzyczna",
"komedia obyczajowa",
"komedia przygodowa",
"Komedia Romantyczna",
"komedia sensacyjna",
"Komedia Sf",
"Komediodramat",
"melodramat",
"musical ",
"thriller",
"Thriller Erotyczny",
"Thriller Sf",
"western",
"western komediowy"
            };
            return categories.Select(c => new SelectListItem() { Text = c, Value = c }).ToList();
        }

        public IList<SelectListItem> GetCountries()
        {
            var list = new string[]
            {
                "Arabskie/USA",
"Argentyna",
"Australia",
"Australia/Dania/USA",
"Australia/Dania/USA/Norwegia",
"Australia/Meksyk/USA",
"Australia/USA",
"Belgia",
"Belgia/Francja",
"Belgia/Francja/Niemcy/USA/Luksemburg/Izrael/Polska",
"Belgia/Szwecja/Norwegia",
"Belgia/USA",
"Brunei/Malezja",
"Brytania",
"Brytania/Chiny",
"Brytania/Cypr",
"Brytania/Hiszpania",
"Brytania/Norwegia",
"Brytania/Polska",
"Brytania/USA",
"Brytania/USA/Chiny",
"Brytania/USA/Meksyk",
"Brytania/USA/Węgry",
"Chiny",
"Chiny/USA",
"Czechy",
"Czechy/Francja/Ukraina/Polska",
"Czechy/Macedonia/Polska",
"Dania",
"Dania/Szwecja",
"Dania/Szwecja/Norwegia",
"Finlandia",
"Finlandia/Niemcy/Belgia",
"Francja",
"Francja/Bułgaria/USA/Hongkong/Hiszpania/Szwecja",
"Francja/Chiny",
"Francja/Japonia/USA",
"Francja/Niemcy",
"Francja/Nigeria/Tanzania/USA/Indie",
"Francja/USA",
"Francja/Węgry",
"Francja/Włochy",
"Francja/Włochy/Hiszpania",
"Hiszpania",
"Hiszpania/Chiny/USA/Węgry",
"Hiszpania/Kuba",
"Holandia/Polska",
"Hongkong/Chiny/USA/Indie",
"Hongkong/Kanada/Chiny/USA",
"Hongkong/Kanada/USA",
"Hongkong/USA",
"Indie",
"Indonezja/USA",
"Irlandia",
"Islandia",
"Izrael",
"Japonia/USA",
"Kanada",
"Kanada/Australia/USA",
"Kanada/Francja",
"Kanada/Japonia/Chiny/USA",
"Kanada/Japonia/USA",
"Kanada/Kolumbia/USA",
"Kanada/Portugalia/USA",
"Kanada/USA",
"Kanada/USA/Serbia",
"Katar/Belgia/Francja/Algieria",
"Kolumbia/Chiny/USA",
"Litwa/Ukraina/Włochy/Polska/Węgry",
"Łotwa/Polska",
"Luksemburg",
"Luksemburg/Polska",
"Malta/USA",
"Meksyk",
"Meksyk/USA",
"Niemcy",
"Niemcy/Holandia",
"Niemcy/USA",
"Norwegia",
"Polska",
"Południowa",
"Portugalia/USA",
"Rosja",
"Rosja/Francja/Kanada/USA",
"Rosja/USA",
"Rosja/Włochy/Polska",
"Rumunia",
"Serbia",
"Słowacja",
"Somalia",
"Szwajcaria/Niemcy",
"Szwecja",
"Szwecja/USA",
"Ukraina",
"Urugwaj",
"USA",
"USA/Hiszpania",
"USA/Indie",
"Węgry",
"Wielka Brytania",
"Włochy",
"Zelandia/USA",
            };
            return list.Select(c => new SelectListItem() { Text = c, Value = c }).ToList();
        }

        public IList<SelectListItem> GetYears()
        {
            var values = Enumerable.Range(1950, 72).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }).ToList();
            values.Last().Selected = true;
            return values;
        }

    }
}
